---
name: Daily Builds
on:
  workflow_dispatch:
  schedule:
    - cron: '8 20 * * *'

# Declare default permissions as read only.
permissions: read-all

jobs:
  trigger_daily_build:
    uses: ./.github/workflows/shippable_builds.yml
    secrets: inherit
    permissions:
      contents: write # For release bumps
      id-token: write # For GCS publishing (ftp.mo)
