name: Markdown CI

on:
  pull_request:
    paths:
      - '**.md'
      - '.github/workflows/markdown.yml'

# Declare default permissions as read only.
permissions: read-all

jobs:
  markdown_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1

      - name: Quality - Spotless Markdown Check
        run: ./gradlew spotlessMarkdownCheck
