name: "Validate Gradle Wrapper"

on:
  push:
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  validate-gradle:
    name: "validate-gradle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: gradle/actions/wrapper-validation@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1
